#!/bin/bash

data=$1
output=$2

python topicmod.py $1 $2 

# Fill in the blank line with the command or commands that will run your
# program using the document information from '$data'. Print your results
# to standard out. 
#
##############################################################################
python topicmod.py $1 $2 
##############################################################################
#
# Make sure the script works by running
# ./topicmod data/news1000.txt
#
